# Generated by Django 3.0.6 on 2020-05-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('mq', models.IntegerField(default=0)),
                ('rooms', models.IntegerField(default=0)),
                ('baths', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
